### ISSUE TITLE
how it will be run in other laptop and how to download and setup plugins

### ISSUE THREAD

**Issue by karanjeet2333** [JohnNtirintis/Bank-Application#1]
hey,
in this project i can't understand how to set up all these files and run my project.

**Comment by JohnNtirintis** [comment]
Hey,

The project is very small and simple, so the process is very straightforward.

1. Clone the repo to get all the files. 
2. Pick the IDE of your choosing (i.e. IntelliJ). 
3. Open it, import the folder with the files from the repo. 
4. Build & run.
